# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_v2.ui'
#
# Created: Sun Jan 16 20:39:40 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(781, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("deprecated/small-mag.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(420, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_layer1 = QtGui.QPushButton(Dialog)
        self.pushButton_layer1.setGeometry(QtCore.QRect(30, 70, 141, 27))
        self.pushButton_layer1.setObjectName("pushButton_layer1")
        self.pushButton_layer2 = QtGui.QPushButton(Dialog)
        self.pushButton_layer2.setGeometry(QtCore.QRect(30, 120, 141, 27))
        self.pushButton_layer2.setObjectName("pushButton_layer2")
        self.pushButton_layer3 = QtGui.QPushButton(Dialog)
        self.pushButton_layer3.setGeometry(QtCore.QRect(30, 170, 141, 27))
        self.pushButton_layer3.setObjectName("pushButton_layer3")
        self.pushButton_layer4 = QtGui.QPushButton(Dialog)
        self.pushButton_layer4.setGeometry(QtCore.QRect(30, 220, 141, 27))
        self.pushButton_layer4.setObjectName("pushButton_layer4")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_layerParams = QtGui.QLabel(Dialog)
        self.label_layerParams.setGeometry(QtCore.QRect(230, 40, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_layerParams.setFont(font)
        self.label_layerParams.setObjectName("label_layerParams")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 270, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_dx = QtGui.QLineEdit(Dialog)
        self.lineEdit_dx.setGeometry(QtCore.QRect(40, 310, 51, 25))
        self.lineEdit_dx.setObjectName("lineEdit_dx")
        self.lineEdit_dy = QtGui.QLineEdit(Dialog)
        self.lineEdit_dy.setGeometry(QtCore.QRect(110, 310, 51, 25))
        self.lineEdit_dy.setObjectName("lineEdit_dy")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 261, 16))
        self.label_4.setObjectName("label_4")
        self.checkBox_layerEn = QtGui.QCheckBox(Dialog)
        self.checkBox_layerEn.setGeometry(QtCore.QRect(240, 70, 87, 21))
        self.checkBox_layerEn.setObjectName("checkBox_layerEn")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(230, 120, 261, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_SatMag = QtGui.QLineEdit(Dialog)
        self.lineEdit_SatMag.setGeometry(QtCore.QRect(230, 140, 151, 24))
        self.lineEdit_SatMag.setObjectName("lineEdit_SatMag")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(490, 40, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_n = QtGui.QLineEdit(Dialog)
        self.lineEdit_n.setGeometry(QtCore.QRect(670, 140, 81, 24))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.lineEdit_jmin = QtGui.QLineEdit(Dialog)
        self.lineEdit_jmin.setGeometry(QtCore.QRect(490, 140, 81, 24))
        self.lineEdit_jmin.setObjectName("lineEdit_jmin")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(490, 120, 261, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_jmax = QtGui.QLineEdit(Dialog)
        self.lineEdit_jmax.setGeometry(QtCore.QRect(580, 140, 81, 24))
        self.lineEdit_jmax.setObjectName("lineEdit_jmax")
        self.lineEdit_nfield = QtGui.QLineEdit(Dialog)
        self.lineEdit_nfield.setGeometry(QtCore.QRect(670, 90, 81, 24))
        self.lineEdit_nfield.setObjectName("lineEdit_nfield")
        self.lineEdit_hzmax = QtGui.QLineEdit(Dialog)
        self.lineEdit_hzmax.setGeometry(QtCore.QRect(580, 90, 81, 24))
        self.lineEdit_hzmax.setObjectName("lineEdit_hzmax")
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(490, 70, 261, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_hzmin = QtGui.QLineEdit(Dialog)
        self.lineEdit_hzmin.setGeometry(QtCore.QRect(490, 90, 81, 21))
        self.lineEdit_hzmin.setObjectName("lineEdit_hzmin")
        self.lineEdit_perK2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_perK2.setGeometry(QtCore.QRect(490, 290, 151, 23))
        self.lineEdit_perK2.setObjectName("lineEdit_perK2")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(490, 270, 261, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_thetaoff = QtGui.QLineEdit(Dialog)
        self.lineEdit_thetaoff.setGeometry(QtCore.QRect(490, 340, 151, 24))
        self.lineEdit_thetaoff.setObjectName("lineEdit_thetaoff")
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(490, 320, 261, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_threadcount = QtGui.QLineEdit(Dialog)
        self.lineEdit_threadcount.setGeometry(QtCore.QRect(20, 480, 151, 24))
        self.lineEdit_threadcount.setObjectName("lineEdit_threadcount")
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(20, 460, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.progressBar_Progress = QtGui.QProgressBar(Dialog)
        self.progressBar_Progress.setGeometry(QtCore.QRect(20, 530, 151, 23))
        self.progressBar_Progress.setProperty("value", 24)
        self.progressBar_Progress.setObjectName("progressBar_Progress")
        self.label_Progress = QtGui.QLabel(Dialog)
        self.label_Progress.setGeometry(QtCore.QRect(20, 510, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_Progress.setFont(font)
        self.label_Progress.setObjectName("label_Progress")
        self.label_GeneratePlot = QtGui.QLabel(Dialog)
        self.label_GeneratePlot.setGeometry(QtCore.QRect(260, 470, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_GeneratePlot.setFont(font)
        self.label_GeneratePlot.setObjectName("label_GeneratePlot")
        self.pushButton_GetLims = QtGui.QPushButton(Dialog)
        self.pushButton_GetLims.setGeometry(QtCore.QRect(320, 530, 111, 27))
        self.pushButton_GetLims.setObjectName("pushButton_GetLims")
        self.pushButton_MakePlot = QtGui.QPushButton(Dialog)
        self.pushButton_MakePlot.setGeometry(QtCore.QRect(200, 530, 111, 27))
        self.pushButton_MakePlot.setObjectName("pushButton_MakePlot")
        self.comboBox_PlotType = QtGui.QComboBox(Dialog)
        self.comboBox_PlotType.setGeometry(QtCore.QRect(200, 500, 231, 26))
        self.comboBox_PlotType.setObjectName("comboBox_PlotType")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.lineEdit_Alpha = QtGui.QLineEdit(Dialog)
        self.lineEdit_Alpha.setGeometry(QtCore.QRect(230, 390, 151, 24))
        self.lineEdit_Alpha.setObjectName("lineEdit_Alpha")
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(230, 370, 261, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_K1 = QtGui.QLineEdit(Dialog)
        self.lineEdit_K1.setGeometry(QtCore.QRect(230, 190, 151, 24))
        self.lineEdit_K1.setObjectName("lineEdit_K1")
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(230, 170, 261, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(200, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(14)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.checkBox_layerFixed = QtGui.QCheckBox(Dialog)
        self.checkBox_layerFixed.setGeometry(QtCore.QRect(240, 90, 87, 21))
        self.checkBox_layerFixed.setObjectName("checkBox_layerFixed")
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(230, 220, 261, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit_layerpos_z = QtGui.QLineEdit(Dialog)
        self.lineEdit_layerpos_z.setGeometry(QtCore.QRect(230, 240, 151, 24))
        self.lineEdit_layerpos_z.setObjectName("lineEdit_layerpos_z")
        self.lineEdit_dz = QtGui.QLineEdit(Dialog)
        self.lineEdit_dz.setGeometry(QtCore.QRect(230, 290, 151, 24))
        self.lineEdit_dz.setObjectName("lineEdit_dz")
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(230, 270, 261, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(230, 320, 261, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_InitMagX = QtGui.QLineEdit(Dialog)
        self.lineEdit_InitMagX.setGeometry(QtCore.QRect(230, 340, 61, 24))
        self.lineEdit_InitMagX.setObjectName("lineEdit_InitMagX")
        self.lineEdit_InitMagY = QtGui.QLineEdit(Dialog)
        self.lineEdit_InitMagY.setGeometry(QtCore.QRect(300, 340, 61, 24))
        self.lineEdit_InitMagY.setObjectName("lineEdit_InitMagY")
        self.lineEdit_InitMagZ = QtGui.QLineEdit(Dialog)
        self.lineEdit_InitMagZ.setGeometry(QtCore.QRect(370, 340, 61, 24))
        self.lineEdit_InitMagZ.setObjectName("lineEdit_InitMagZ")
        self.lineEdit_SampTemp = QtGui.QLineEdit(Dialog)
        self.lineEdit_SampTemp.setGeometry(QtCore.QRect(490, 240, 151, 23))
        self.lineEdit_SampTemp.setObjectName("lineEdit_SampTemp")
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(490, 220, 261, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(490, 170, 261, 16))
        self.label_24.setObjectName("label_24")
        self.lineEdit_IntegrationTime = QtGui.QLineEdit(Dialog)
        self.lineEdit_IntegrationTime.setGeometry(QtCore.QRect(490, 190, 151, 23))
        self.lineEdit_IntegrationTime.setObjectName("lineEdit_IntegrationTime")
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(580, 450, 191, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 480, 191, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_numFrames = QtGui.QLabel(Dialog)
        self.label_numFrames.setGeometry(QtCore.QRect(450, 480, 101, 16))
        self.label_numFrames.setObjectName("label_numFrames")
        self.lineEdit_numFrames = QtGui.QLineEdit(Dialog)
        self.lineEdit_numFrames.setGeometry(QtCore.QRect(450, 500, 71, 24))
        self.lineEdit_numFrames.setObjectName("lineEdit_numFrames")
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 420, 191, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 340, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_25 = QtGui.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(10, 360, 261, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_af_12 = QtGui.QLineEdit(Dialog)
        self.lineEdit_af_12.setGeometry(QtCore.QRect(10, 380, 61, 26))
        self.lineEdit_af_12.setObjectName("lineEdit_af_12")
        self.lineEdit_af_13 = QtGui.QLineEdit(Dialog)
        self.lineEdit_af_13.setGeometry(QtCore.QRect(80, 380, 61, 26))
        self.lineEdit_af_13.setObjectName("lineEdit_af_13")
        self.lineEdit_af_14 = QtGui.QLineEdit(Dialog)
        self.lineEdit_af_14.setGeometry(QtCore.QRect(150, 380, 61, 26))
        self.lineEdit_af_14.setObjectName("lineEdit_af_14")
        self.lineEdit_af_23 = QtGui.QLineEdit(Dialog)
        self.lineEdit_af_23.setGeometry(QtCore.QRect(10, 430, 61, 26))
        self.lineEdit_af_23.setObjectName("lineEdit_af_23")
        self.lineEdit_af_24 = QtGui.QLineEdit(Dialog)
        self.lineEdit_af_24.setGeometry(QtCore.QRect(80, 430, 61, 25))
        self.lineEdit_af_24.setObjectName("lineEdit_af_24")
        self.lineEdit_af_34 = QtGui.QLineEdit(Dialog)
        self.lineEdit_af_34.setGeometry(QtCore.QRect(150, 430, 61, 26))
        self.lineEdit_af_34.setObjectName("lineEdit_af_34")
        self.label_26 = QtGui.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(10, 410, 261, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(140, 410, 261, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_Pol = QtGui.QLineEdit(Dialog)
        self.lineEdit_Pol.setGeometry(QtCore.QRect(230, 440, 151, 24))
        self.lineEdit_Pol.setObjectName("lineEdit_Pol")
        self.label_28 = QtGui.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(230, 420, 261, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_relax = QtGui.QLineEdit(Dialog)
        self.lineEdit_relax.setGeometry(QtCore.QRect(490, 390, 151, 24))
        self.lineEdit_relax.setObjectName("lineEdit_relax")
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(490, 370, 261, 16))
        self.label_16.setObjectName("label_16")
        self.checkBox_fieldInPlane = QtGui.QCheckBox(Dialog)
        self.checkBox_fieldInPlane.setGeometry(QtCore.QRect(640, 40, 121, 21))
        self.checkBox_fieldInPlane.setObjectName("checkBox_fieldInPlane")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.close)
        QtCore.QObject.connect(self.pushButton_layer1, QtCore.SIGNAL("clicked()"), Dialog.handleLayer1Button)
        QtCore.QObject.connect(self.pushButton_layer2, QtCore.SIGNAL("clicked()"), Dialog.handleLayer2Button)
        QtCore.QObject.connect(self.pushButton_layer3, QtCore.SIGNAL("clicked()"), Dialog.handleLayer3Button)
        QtCore.QObject.connect(self.pushButton_layer4, QtCore.SIGNAL("clicked()"), Dialog.handleLayer4Button)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.runHsweepSlot)
        QtCore.QObject.connect(self.pushButton_MakePlot, QtCore.SIGNAL("clicked()"), Dialog.makePlotSlot)
        QtCore.QObject.connect(self.pushButton_GetLims, QtCore.SIGNAL("clicked()"), Dialog.handleSetLimits)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), Dialog.handleSaveParamsToFile)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Dialog.handleLoadParamsFromFile)
        QtCore.QObject.connect(self.comboBox_PlotType, QtCore.SIGNAL("activated(int)"), Dialog.handlePlotTypeSelect)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), Dialog.handleTimeDepDialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_layer1.setText(QtGui.QApplication.translate("Dialog", "Layer 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_layer2.setText(QtGui.QApplication.translate("Dialog", "Layer 2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_layer3.setText(QtGui.QApplication.translate("Dialog", "Layer 3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_layer4.setText(QtGui.QApplication.translate("Dialog", "Layer 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Layer Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_layerParams.setText(QtGui.QApplication.translate("Dialog", "Layer n Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Sample Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Dims of sample (x, y, in nm)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_layerEn.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Saturation Magnetization, in A/m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Global Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Min/Max Current Density, and # of points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Min/Max Magnetic Field, A/m, & # of points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Percentage that K2 is of K1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Theta Offset from Z-axis, degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Number of CPU Threads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Progress.setText(QtGui.QApplication.translate("Dialog", "Run Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.label_GeneratePlot.setText(QtGui.QApplication.translate("Dialog", "Generate Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_GetLims.setText(QtGui.QApplication.translate("Dialog", "Limits from Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_MakePlot.setText(QtGui.QApplication.translate("Dialog", "Make The Plot!", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(0, QtGui.QApplication.translate("Dialog", "Sweep Up Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(1, QtGui.QApplication.translate("Dialog", "Sweep Down Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(2, QtGui.QApplication.translate("Dialog", "Sweep Up - Down (Difference)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(3, QtGui.QApplication.translate("Dialog", "Sweep Up + Down (Sum)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(4, QtGui.QApplication.translate("Dialog", "All Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(5, QtGui.QApplication.translate("Dialog", "Single Point", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(6, QtGui.QApplication.translate("Dialog", "Single Point, Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(7, QtGui.QApplication.translate("Dialog", "H sweep only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(8, QtGui.QApplication.translate("Dialog", "J sweep only", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Alpha - Gilbert\'s Damping Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Layer Anisotropy (J/m³)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Spinsim_GSL Graphical Interface V2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_layerFixed.setText(QtGui.QApplication.translate("Dialog", "Fixed?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Distance from bottom on z (nm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Layer thickness (nm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Initial Magnetization (x,y,z)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Temperature of Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Integration Time, in seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Save Parameters to File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Dialog", "Load Parameters from File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_numFrames.setText(QtGui.QApplication.translate("Dialog", "# of Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Edit AC Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "AF Coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Layer 1 to 2,3,4, in μJ/m²", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Layer 2 to 3,4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "Layer 3 to 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "Polarisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Relaxation Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fieldInPlane.setText(QtGui.QApplication.translate("Dialog", "Field In Plane?", None, QtGui.QApplication.UnicodeUTF8))

