# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timedep_dialog.ui'
#
# Created: Sun Jan 16 20:39:40 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(776, 428)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(360, 380, 361, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 10, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(14)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(490, 50, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.j_dep_ampl = QtGui.QLineEdit(Dialog)
        self.j_dep_ampl.setGeometry(QtCore.QRect(10, 120, 71, 26))
        self.j_dep_ampl.setObjectName("j_dep_ampl")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 271, 16))
        self.label_8.setObjectName("label_8")
        self.j_dep_freq = QtGui.QLineEdit(Dialog)
        self.j_dep_freq.setGeometry(QtCore.QRect(90, 120, 71, 26))
        self.j_dep_freq.setObjectName("j_dep_freq")
        self.j_dep_phas = QtGui.QLineEdit(Dialog)
        self.j_dep_phas.setGeometry(QtCore.QRect(170, 120, 71, 26))
        self.j_dep_phas.setObjectName("j_dep_phas")
        self.j_indep_ampl = QtGui.QLineEdit(Dialog)
        self.j_indep_ampl.setGeometry(QtCore.QRect(10, 190, 71, 26))
        self.j_indep_ampl.setObjectName("j_indep_ampl")
        self.j_indep_freq = QtGui.QLineEdit(Dialog)
        self.j_indep_freq.setGeometry(QtCore.QRect(90, 190, 71, 26))
        self.j_indep_freq.setObjectName("j_indep_freq")
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 271, 16))
        self.label_9.setObjectName("label_9")
        self.j_indep_phas = QtGui.QLineEdit(Dialog)
        self.j_indep_phas.setGeometry(QtCore.QRect(170, 190, 71, 26))
        self.j_indep_phas.setObjectName("j_indep_phas")
        self.j_userdep_file = QtGui.QLineEdit(Dialog)
        self.j_userdep_file.setGeometry(QtCore.QRect(10, 260, 241, 26))
        self.j_userdep_file.setObjectName("j_userdep_file")
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(90, 240, 271, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(90, 320, 271, 16))
        self.label_11.setObjectName("label_11")
        self.j_userindep_file = QtGui.QLineEdit(Dialog)
        self.j_userindep_file.setGeometry(QtCore.QRect(10, 340, 241, 26))
        self.j_userindep_file.setObjectName("j_userindep_file")
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(490, 320, 271, 16))
        self.label_12.setObjectName("label_12")
        self.hz_dep_ampl = QtGui.QLineEdit(Dialog)
        self.hz_dep_ampl.setGeometry(QtCore.QRect(410, 120, 71, 26))
        self.hz_dep_ampl.setObjectName("hz_dep_ampl")
        self.hz_dep_freq = QtGui.QLineEdit(Dialog)
        self.hz_dep_freq.setGeometry(QtCore.QRect(490, 120, 71, 26))
        self.hz_dep_freq.setObjectName("hz_dep_freq")
        self.hz_indep_freq = QtGui.QLineEdit(Dialog)
        self.hz_indep_freq.setGeometry(QtCore.QRect(490, 190, 71, 26))
        self.hz_indep_freq.setObjectName("hz_indep_freq")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(410, 220, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(410, 80, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(410, 150, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.hz_indep_ampl = QtGui.QLineEdit(Dialog)
        self.hz_indep_ampl.setGeometry(QtCore.QRect(410, 190, 71, 26))
        self.hz_indep_ampl.setObjectName("hz_indep_ampl")
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(410, 100, 271, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(410, 170, 271, 16))
        self.label_17.setObjectName("label_17")
        self.hz_indep_phas = QtGui.QLineEdit(Dialog)
        self.hz_indep_phas.setGeometry(QtCore.QRect(570, 190, 71, 26))
        self.hz_indep_phas.setObjectName("hz_indep_phas")
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(410, 300, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(490, 240, 271, 16))
        self.label_19.setObjectName("label_19")
        self.hz_dep_phas = QtGui.QLineEdit(Dialog)
        self.hz_dep_phas.setGeometry(QtCore.QRect(570, 120, 71, 26))
        self.hz_dep_phas.setObjectName("hz_dep_phas")
        self.hz_userdep_file = QtGui.QLineEdit(Dialog)
        self.hz_userdep_file.setGeometry(QtCore.QRect(410, 260, 241, 26))
        self.hz_userdep_file.setObjectName("hz_userdep_file")
        self.hz_userindep_file = QtGui.QLineEdit(Dialog)
        self.hz_userindep_file.setGeometry(QtCore.QRect(410, 340, 241, 26))
        self.hz_userindep_file.setObjectName("hz_userindep_file")
        self.j_sin_dep_en = QtGui.QCheckBox(Dialog)
        self.j_sin_dep_en.setGeometry(QtCore.QRect(260, 120, 86, 21))
        self.j_sin_dep_en.setObjectName("j_sin_dep_en")
        self.j_sin_indep_en = QtGui.QCheckBox(Dialog)
        self.j_sin_indep_en.setGeometry(QtCore.QRect(260, 190, 86, 21))
        self.j_sin_indep_en.setObjectName("j_sin_indep_en")
        self.j_dc_en = QtGui.QCheckBox(Dialog)
        self.j_dc_en.setGeometry(QtCore.QRect(170, 50, 111, 21))
        self.j_dc_en.setObjectName("j_dc_en")
        self.j_userdep_en = QtGui.QCheckBox(Dialog)
        self.j_userdep_en.setGeometry(QtCore.QRect(260, 260, 86, 21))
        self.j_userdep_en.setObjectName("j_userdep_en")
        self.j_userindep_en = QtGui.QCheckBox(Dialog)
        self.j_userindep_en.setGeometry(QtCore.QRect(260, 340, 86, 21))
        self.j_userindep_en.setObjectName("j_userindep_en")
        self.hz_userdep_en = QtGui.QCheckBox(Dialog)
        self.hz_userdep_en.setGeometry(QtCore.QRect(660, 260, 86, 21))
        self.hz_userdep_en.setObjectName("hz_userdep_en")
        self.hz_dc_en = QtGui.QCheckBox(Dialog)
        self.hz_dc_en.setGeometry(QtCore.QRect(650, 50, 111, 21))
        self.hz_dc_en.setObjectName("hz_dc_en")
        self.hz_sin_indep_en = QtGui.QCheckBox(Dialog)
        self.hz_sin_indep_en.setGeometry(QtCore.QRect(660, 190, 86, 21))
        self.hz_sin_indep_en.setObjectName("hz_sin_indep_en")
        self.hz_sin_dep_en = QtGui.QCheckBox(Dialog)
        self.hz_sin_dep_en.setGeometry(QtCore.QRect(660, 120, 86, 21))
        self.hz_sin_dep_en.setObjectName("hz_sin_dep_en")
        self.hz_userindep_en = QtGui.QCheckBox(Dialog)
        self.hz_userindep_en.setGeometry(QtCore.QRect(660, 340, 86, 21))
        self.hz_userindep_en.setObjectName("hz_userindep_en")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Time Dependent Function Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Dependent AC Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Independent AC Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Dependent User Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Independent User Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Current (J)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Magnetic Field (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Amplitude/Frequency/Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Amplitude/Frequency/Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Dependent User Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Dependent AC Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Independent AC Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Amplitude/Frequency/Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Amplitude/Frequency/Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Amplitude-Independent User Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.j_sin_dep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.j_sin_indep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.j_dc_en.setText(QtGui.QApplication.translate("Dialog", "DC Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.j_userdep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.j_userindep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.hz_userdep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.hz_dc_en.setText(QtGui.QApplication.translate("Dialog", "DC Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.hz_sin_indep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.hz_sin_dep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))
        self.hz_userindep_en.setText(QtGui.QApplication.translate("Dialog", "Enabled?", None, QtGui.QApplication.UnicodeUTF8))

