# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui.ui'
#
# Created: Sun Feb  7 19:55:26 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(912, 524)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("deprecated/small-mag.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(560, 480, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit_K1 = QtGui.QLineEdit(Dialog)
        self.lineEdit_K1.setGeometry(QtCore.QRect(10, 100, 113, 24))
        self.lineEdit_K1.setObjectName("lineEdit_K1")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 80, 291, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(14)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 291, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_Alpha = QtGui.QLineEdit(Dialog)
        self.lineEdit_Alpha.setGeometry(QtCore.QRect(10, 150, 113, 24))
        self.lineEdit_Alpha.setObjectName("lineEdit_Alpha")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 291, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_Ms = QtGui.QLineEdit(Dialog)
        self.lineEdit_Ms.setGeometry(QtCore.QRect(10, 200, 113, 24))
        self.lineEdit_Ms.setObjectName("lineEdit_Ms")
        self.lineEdit_Mrs = QtGui.QLineEdit(Dialog)
        self.lineEdit_Mrs.setGeometry(QtCore.QRect(10, 250, 113, 24))
        self.lineEdit_Mrs.setObjectName("lineEdit_Mrs")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 311, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 280, 311, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_dx = QtGui.QLineEdit(Dialog)
        self.lineEdit_dx.setGeometry(QtCore.QRect(10, 304, 121, 20))
        self.lineEdit_dx.setObjectName("lineEdit_dx")
        self.lineEdit_dy = QtGui.QLineEdit(Dialog)
        self.lineEdit_dy.setGeometry(QtCore.QRect(10, 350, 121, 20))
        self.lineEdit_dy.setObjectName("lineEdit_dy")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 330, 311, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 380, 311, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_dz = QtGui.QLineEdit(Dialog)
        self.lineEdit_dz.setGeometry(QtCore.QRect(10, 400, 121, 20))
        self.lineEdit_dz.setObjectName("lineEdit_dz")
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(360, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_jmax = QtGui.QLineEdit(Dialog)
        self.lineEdit_jmax.setGeometry(QtCore.QRect(360, 140, 113, 24))
        self.lineEdit_jmax.setObjectName("lineEdit_jmax")
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(360, 120, 291, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_hzmax = QtGui.QLineEdit(Dialog)
        self.lineEdit_hzmax.setGeometry(QtCore.QRect(360, 240, 113, 24))
        self.lineEdit_hzmax.setObjectName("lineEdit_hzmax")
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(360, 220, 291, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_t_f = QtGui.QLineEdit(Dialog)
        self.lineEdit_t_f.setGeometry(QtCore.QRect(360, 290, 113, 20))
        self.lineEdit_t_f.setObjectName("lineEdit_t_f")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(360, 270, 291, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_perK2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_perK2.setGeometry(QtCore.QRect(360, 340, 113, 20))
        self.lineEdit_perK2.setObjectName("lineEdit_perK2")
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(360, 320, 291, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_thetaoff = QtGui.QLineEdit(Dialog)
        self.lineEdit_thetaoff.setGeometry(QtCore.QRect(360, 390, 113, 20))
        self.lineEdit_thetaoff.setObjectName("lineEdit_thetaoff")
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(360, 370, 341, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_n = QtGui.QLineEdit(Dialog)
        self.lineEdit_n.setGeometry(QtCore.QRect(360, 440, 113, 20))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(360, 420, 381, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(360, 470, 381, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_nfield = QtGui.QLineEdit(Dialog)
        self.lineEdit_nfield.setGeometry(QtCore.QRect(360, 490, 113, 20))
        self.lineEdit_nfield.setObjectName("lineEdit_nfield")
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(650, 50, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_threadcount = QtGui.QLineEdit(Dialog)
        self.lineEdit_threadcount.setGeometry(QtCore.QRect(650, 100, 113, 24))
        self.lineEdit_threadcount.setObjectName("lineEdit_threadcount")
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(650, 80, 291, 16))
        self.label_19.setObjectName("label_19")
        self.progressBar_Progress = QtGui.QProgressBar(Dialog)
        self.progressBar_Progress.setEnabled(True)
        self.progressBar_Progress.setGeometry(QtCore.QRect(750, 370, 131, 23))
        self.progressBar_Progress.setProperty("value", 0)
        self.progressBar_Progress.setObjectName("progressBar_Progress")
        self.label_Progress = QtGui.QLabel(Dialog)
        self.label_Progress.setGeometry(QtCore.QRect(750, 350, 131, 16))
        self.label_Progress.setObjectName("label_Progress")
        self.comboBox_PlotType = QtGui.QComboBox(Dialog)
        self.comboBox_PlotType.setGeometry(QtCore.QRect(650, 170, 191, 26))
        self.comboBox_PlotType.setObjectName("comboBox_PlotType")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.comboBox_PlotType.addItem("")
        self.label_GeneratePlot = QtGui.QLabel(Dialog)
        self.label_GeneratePlot.setGeometry(QtCore.QRect(650, 140, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_GeneratePlot.setFont(font)
        self.label_GeneratePlot.setObjectName("label_GeneratePlot")
        self.pushButton_MakePlot = QtGui.QPushButton(Dialog)
        self.pushButton_MakePlot.setGeometry(QtCore.QRect(650, 200, 111, 27))
        self.pushButton_MakePlot.setObjectName("pushButton_MakePlot")
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(360, 70, 291, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit_jmin = QtGui.QLineEdit(Dialog)
        self.lineEdit_jmin.setGeometry(QtCore.QRect(360, 90, 113, 24))
        self.lineEdit_jmin.setObjectName("lineEdit_jmin")
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(360, 170, 291, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_hzmin = QtGui.QLineEdit(Dialog)
        self.lineEdit_hzmin.setGeometry(QtCore.QRect(360, 190, 113, 24))
        self.lineEdit_hzmin.setObjectName("lineEdit_hzmin")
        self.pushButton_GetLims = QtGui.QPushButton(Dialog)
        self.pushButton_GetLims.setGeometry(QtCore.QRect(650, 240, 111, 27))
        self.pushButton_GetLims.setObjectName("pushButton_GetLims")
        self.pushButton_MakePlot_2 = QtGui.QPushButton(Dialog)
        self.pushButton_MakePlot_2.setGeometry(QtCore.QRect(770, 200, 111, 27))
        self.pushButton_MakePlot_2.setObjectName("pushButton_MakePlot_2")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.close)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.runHsweepSlot)
        QtCore.QObject.connect(self.pushButton_MakePlot, QtCore.SIGNAL("clicked()"), Dialog.makePlotSlot)
        QtCore.QObject.connect(self.pushButton_GetLims, QtCore.SIGNAL("clicked()"), Dialog.handleSetLimits)
        QtCore.QObject.connect(self.pushButton_MakePlot_2, QtCore.SIGNAL("clicked()"), Dialog.handleSinglePlot)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Spinsim_GSL GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "K1: Free Layer Anisotropy Constant, J/(m**3)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Spinsim_GSL Graphical Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Constants to Use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Alpha: Gilbert\'s damping factor, dimensionless", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "MS: Free Layer Saturation Magnetization, A/m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "MRS: Pinned Layer Saturation Magnetization, A/m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "dx: X-axis parameter for demag tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "dy: Y-axis parameter for demag tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "dz: Z-axis parameter for demag tensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Parameters to Use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "J_MAX: The maximum current density", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "HZ_MAX: The maximum current density to use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "t_f: Integration Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "%K2 - the percentage that K2 is of K1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "theta_offset: Offset from z-axis to apply external field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "n: # of current density points in range (-J_MAX, J_MAX)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "nfield: # of ext H-field points in range (-HZ_MAX, HZ_MAX)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "System Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Number of Threads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Progress.setText(QtGui.QApplication.translate("Dialog", "Current Run Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(0, QtGui.QApplication.translate("Dialog", "Sweep Up Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(1, QtGui.QApplication.translate("Dialog", "Sweep Down Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(2, QtGui.QApplication.translate("Dialog", "Sweep Up - Down (Difference)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(3, QtGui.QApplication.translate("Dialog", "Sweep Up + Down (Sum)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PlotType.setItemText(4, QtGui.QApplication.translate("Dialog", "All Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_GeneratePlot.setText(QtGui.QApplication.translate("Dialog", "Generate Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_MakePlot.setText(QtGui.QApplication.translate("Dialog", "Make The Plot!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "J_MIN: The minimum current density", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "HZ_MIN: The minimum current density to use", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_GetLims.setText(QtGui.QApplication.translate("Dialog", "Limits from Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_MakePlot_2.setText(QtGui.QApplication.translate("Dialog", "Plot Single Point", None, QtGui.QApplication.UnicodeUTF8))

